title: Projects over The Coding Train (by Daniel Shiffman)
author: Nicolas Rivollet
email: nicolas.rivollet@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Here is a list of projects made from the Coding Train, 
  a YouTube channel dedicated to beginner-friendly creative coding tutorials and challenges.

# social links
twitter_username: nrivollet
github_username:  nicolasrivollet

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
